export const ITEM_ORDER = [
  'FRUIT_STRAWBERRY',
  'FRUIT_BLUEBERRY',
  'FRUIT_APPLE',
  'FRUIT_MANGO',
  'FRUIT_COCONUT',
  'FRUIT_OLIVE',
  'SEED_STRAWBERRY',
  'SEED_BLUEBERRY',
  'SEED_APPLE',
  'SEED_MANGO',
  'SEED_COCONUT',
  'SEED_OLIVE',
  'MEAT_SMALL',
  'MEAT_MEDIUM',
  'MEAT_LARGE',
];

export const ITEM_PARAMS = {
  FRUIT_STRAWBERRY: {
    template: 'fruit',
    body: '#d93a47',
    shade: '#b9232f',
    stem: '#4f8a2f',
    seed: '#f9da7a',
    rX: 8,
    rY: 9,
  },
  FRUIT_BLUEBERRY: {
    template: 'fruit',
    body: '#4c5fd1',
    shade: '#3444a2',
    stem: '#7db56a',
    seed: '#c9ddff',
    rX: 7,
    rY: 7,
  },
  FRUIT_APPLE: {
    template: 'fruit',
    body: '#c92f2d',
    shade: '#8d1f1e',
    stem: '#5a3a1b',
    seed: '#f2e1b0',
    rX: 9,
    rY: 8,
  },
  FRUIT_MANGO: {
    template: 'fruit',
    body: '#f2a31d',
    shade: '#d1810d',
    stem: '#53762d',
    seed: '#ffebae',
    rX: 9,
    rY: 7,
  },
  FRUIT_COCONUT: {
    template: 'fruit',
    body: '#8a5b33',
    shade: '#6a4120',
    stem: '#b9a07e',
    seed: '#dbc8a8',
    rX: 8,
    rY: 8,
  },
  FRUIT_OLIVE: {
    template: 'fruit',
    body: '#6f8a2f',
    shade: '#4f661f',
    stem: '#93a874',
    seed: '#d8e2c0',
    rX: 7,
    rY: 6,
  },

  SEED_STRAWBERRY: {
    template: 'seed',
    shell: '#8e5528',
    core: '#b87945',
    accent: '#e5be8a',
    rX: 4,
    rY: 6,
  },
  SEED_BLUEBERRY: {
    template: 'seed',
    shell: '#7f4e2f',
    core: '#a16c46',
    accent: '#dcbf93',
    rX: 4,
    rY: 5,
  },
  SEED_APPLE: {
    template: 'seed',
    shell: '#65401f',
    core: '#8a5b33',
    accent: '#ceb085',
    rX: 5,
    rY: 6,
  },
  SEED_MANGO: {
    template: 'seed',
    shell: '#7b562f',
    core: '#a87949',
    accent: '#dbc59d',
    rX: 5,
    rY: 7,
  },
  SEED_COCONUT: {
    template: 'seed',
    shell: '#5b3a1d',
    core: '#7f5a32',
    accent: '#caa981',
    rX: 6,
    rY: 6,
  },
  SEED_OLIVE: {
    template: 'seed',
    shell: '#6b4a27',
    core: '#8a6440',
    accent: '#cbb48c',
    rX: 4,
    rY: 5,
  },

  MEAT_SMALL: {
    template: 'meat',
    flesh: '#d36c62',
    fat: '#f3dcc8',
    edge: '#a74a42',
    veins: '#d89086',
    w: 16,
    h: 11,
  },
  MEAT_MEDIUM: {
    template: 'meat',
    flesh: '#c95f57',
    fat: '#f0d6bf',
    edge: '#9a3f38',
    veins: '#d28278',
    w: 19,
    h: 12,
  },
  MEAT_LARGE: {
    template: 'meat',
    flesh: '#b8524a',
    fat: '#ebd0b7',
    edge: '#87352f',
    veins: '#cb756c',
    w: 22,
    h: 13,
  },
};
